export const allTypes = [
    '---------------------------',
    'News',
    'Recipe',
    'Recyclable Alternative',
    'Wildlife',
    'Natural Health',
    'Fitness',
    'Gas Alternatives',
    'Green House Effect',
    'Just Spreading Love',
    'Music',
    'Politics',
    'United Nations',
    'Soka Gakkai International',
    'Spirituality',
    'Organics',
    'How to DIY',
    'Suggestion to the Creator'
]